# Prepare dataset to push to GBQ

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/Users/other/Documents/Sweet-Sense-AI/data/dataset/init_data.csv")
df.shape

/var/folders/sw/1bzhdyc54kjcrbkr4dmftfb40000gp/T/ipykernel_87336/2933564486.py:1: DtypeWarning: Columns (0: PCDMDECN, 1: EXACTOT1, 2: EXACTOT2, 3: DLYOTHER, 4: RCSRACE1, 5: RCHISLA1, 6: RCSBIRTH, 7: HLTHCVRG, 8: TYPEINDS, 9: TYPEWORK, 10: INTVID, 11: MRACE, 12: RCSRACE, 13: RCVFVCH4, 14: CRACEORG, 15: MRACEORG) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/Users/other/Documents/Sweet-Sense-AI/data/dataset/init_data.csv")

(2380047, 644)

In [3]:
pd.set_option('display.max_columns', 500)
df.head()

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENUM,PVTRESD1,COLGHOUS,STATERES,CELLFON3,LADULT,NUMADULT,NUMMEN,NUMWOMEN,CTELNUM1,CELLFON2,CADULT,PVTRESD2,CCLGHOUS,CSTATE,LANDLINE,HHADULT,GENHLTH,PHYSHLTH,MENTHLTH,POORHLTH,HLTHPLN1,PERSDOC2,MEDCOST,CHECKUP1,BPHIGH4,BPMEDS,BLOODCHO,CHOLCHK,TOLDHI2,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNCR,CHCOCNCR,CHCCOPD1,HAVARTH3,ADDEPEV2,CHCKIDNY,DIABETE3,DIABAGE2,SEX,MARITAL,EDUCA,RENTHOM1,NUMHHOL2,NUMPHON2,CPDEMO1,VETERAN3,EMPLOY1,CHILDREN,INCOME2,INTERNET,WEIGHT2,HEIGHT3,PREGNANT,QLACTLM2,USEEQUIP,BLIND,DECIDE,DIFFWALK,DIFFDRES,DIFFALON,SMOKE100,SMOKDAY2,STOPSMK2,LASTSMK2,USENOW3,ALCDAY5,AVEDRNK2,DRNK3GE5,MAXDRNKS,FRUITJU1,FRUIT1,FVBEANS,FVGREEN,FVORANG,VEGETAB1,EXERANY2,EXRACT11,EXEROFT1,EXERHMM1,EXRACT21,EXEROFT2,EXERHMM2,STRENGTH,LMTJOIN3,ARTHDIS2,ARTHSOCL,JOINPAIN,SEATBELT,FLUSHOT6,FLSHTMY2,IMFVPLAC,PNEUVAC3,HIVTST6,HIVTSTD3,WHRTST10,PDIABTST,PREDIAB1,INSULIN,BLDSUGAR,FEETCHK2,DOCTDIAB,CHKHEMO3,FEETCHK,EYEEXAM,DIABEYE,DIABEDU,PAINACT2,QLMENTL2,QLSTRES2,QLHLTH2,CAREGIV1,CRGVREL1,CRGVLNG1,CRGVHRS1,CRGVPRB1,CRGVPERS,CRGVHOUS,CRGVMST2,CRGVEXPT,VIDFCLT2,VIREDIF3,VIPRFVS2,VINOCRE2,VIEYEXM2,VIINSUR2,VICTRCT4,VIGLUMA2,VIMACDG2,CIMEMLOS,CDHOUSE,CDASSIST,CDHELP,CDSOCIAL,CDDISCUS,WTCHSALT,LONGWTCH,DRADVISE,ASTHMAGE,ASATTACK,ASERVIST,ASDRVIST,ASRCHKUP,ASACTLIM,ASYMPTOM,ASNOSLEP,ASTHMED3,ASINHALR,HAREHAB1,STREHAB1,CVDASPRN,ASPUNSAF,RLIVPAIN,RDUCHART,RDUCSTRK,ARTTODAY,ARTHWGT,ARTHEXER,ARTHEDU,TETANUS,HPVADVC2,HPVADSHT,SHINGLE2,HADMAM,HOWLONG,HADPAP2,LASTPAP2,HPVTEST,HPLSTTST,HADHYST2,PROFEXAM,LENGEXAM,BLDSTOOL,LSTBLDS3,HADSIGM3,HADSGCO1,LASTSIG3,PCPSAAD2,PCPSADI1,PCPSARE1,PSATEST1,PSATIME,PCPSARS1,PCPSADE1,PCDMDECN,SCNTMNY1,SCNTMEL1,SCNTPAID,SCNTWRK1,SCNTLPAD,SCNTLWK1,SXORIENT,TRNSGNDR,RCSGENDR,RCSRLTN2,CASTHDX2,CASTHNO2,EMTSUPRT,LSATISFY,ADPLEASR,ADDOWN,ADSLEEP,ADENERGY,ADEAT1,ADFAIL,ADTHINK,ADMOVE,MISTMNT,ADANXEV,QSTVER,QSTLANG,EXACTOT1,EXACTOT2,MSCODE,_STSTR,_STRWT,_RAWRAKE,_WT2RAKE,_CHISPNC,_CRACE1,_CPRACE,_CLLCPWT,_DUALUSE,_DUALCOR,_LLCPWT,_RFHLTH,_HCVU651,_RFHYPE5,_CHOLCHK,_RFCHOL,_MICHD,_LTASTH1,_CASTHM1,_ASTHMS1,_DRDXAR1,_PRACE1,_MRACE1,...,_COL10YR,_HFOB3YR,_FS5YR,_FOBTFS,_CRCREC,_IMPEDUC,_IMPMRTL,_IMPHOME,RCSBRAC1,RCSRACE1,RCHISLA1,RCSBIRTH,CPDEMO4,HLTHCVRG,MEDBILLS,SSBSUGAR,SSBFRUT2,MISNERVS,MISHOPLS,MISRSTLS,MISDEPRD,MISEFFRT,MISWTLES,MISNOWRK,MISTRHLP,MISPHLPF,SCNTMONY,SCNTMEAL,PCTCELL,TYPEINDS,TYPEWORK,_GEOSTR,_DENSTR2,PRECALL,REPNUM,REPDEPTH,INTVID,NATTMPTS,NRECSEL,NRECSTR,PVTRESID,CELLFON,CHCVISN1,AGE,HISPANC2,MRACE,ORACE2,EMPLOY,CTYCODE1,FLUSHOT5,PCPSAAD1,HIVRISK3,VIREDIF2,SSBSUGR1,SSBFRUT1,SSBCALRI,NUMBURN2,QLREST2,SLEPTIME,SLEPSNOR,SLEPDAY,SLEPDRIV,WRKHCF1,DIRCONT1,DRHPAD1,HAVHPAD,SHINGLE1,TNSARCV,TNSARCNT,TNSASHT1,PCPSADEC,GPWELPR3,GP3DYWTR,GP3DYFD1,GP3DYPRS,GPBATRAD,GPFLSLIT,GPEMRCM1,GPEMRIN1,GPVACPL1,GPMNDEVC,GPNOTEV1,VHCOMBAT,VHDRPTSD,VHDRTBI,VHCOUNSL,VHTAKLIF,VHSUICID,COPDTEST,COPDQOL,COPDDOC,COPDHOSP,COPDMEDS,ACEDEPRS,ACEDRINK,ACEDRUGS,ACEPRISN,ACEDIVRC,ACEPUNCH,ACEHURT,ACESWEAR,ACETOUCH,ACETTHEM,ACEHVSEX,RCHISLAT,RCSRACE,RCSBRACE,FLUSHCH2,RCVFVCH4,WHRTST8,HIVRDTST,CALLBACK,ADLTCHLD,RSPSTATE,_RAW,_WT2,_REGION,_IMPAGE,O_STATE,CRACEORG,CRACEASC,_CRACE,_RAWCH,_WT2CH,CHILDAGE,_CLCPM01,_CLCPM02,_CLCPM03,_CLCPM04,_CLCPM05,_LLCPM01,_LLCPM02,_LLCPM03,_LLCPM04,_LLCPM05,_LLCPM06,_LLCPM07,_LLCPM08,_LLCPM09,_LLCPM10,_LLCPM11,_LLCPM12,MRACEORG,MRACEASC,_PRACE,_MRACE,RACE2,_RACEG2,_RACEGR2,_RACE_G,_CNRACE,_CNRACEC,_FLSHOT5,CHCCOPD,CHCVISON,CPDEMO2,CPDEMO3,EXRACT01,EXRACT02,SSBFRUIT,PFPPREPR,PFPPRGNT,PFPPRVNT,TYPCNTR6,NOBCUSE4,FPCHLDF2,PFPVITMN,VIDFCLT3,VIPRFVS3,VINOCRE3,VIEYEXM3,VIINSUR3,VICTRCT3,VIGLUMA3,VIMACDG3,BPEATHBT,BPSALT,BPALCHOL,BPEXER,BPEATADV,BPSLTADV,BPALCADV,BPEXRADV,BPMEDADV,BPHI2MR,HASYMP1,HASYMP2,HASYMP3,HASYMP4,HASYMP5,HASYMP6,STRSYMP1,STRSYMP2,STRSYMP3,STRSYMP4,STRSYMP5,STRSYMP6,FIRSTAID,PCPSAREC,PCPSARSN,PCPSAADV,PCPSADIS,PROSTATE,SMCQUITL,SMCTRYQT,SMCCALQT,SMCPROGQ,SMCCNSLQ,SMCMEDQT,SMCTIMEQ,SMCPLANQ,SHSNWRK1,SHSNHOM1,SHSRIDEV,SHSINPUB,SHSHOMES,SHSVHICL,SHSALOW1,CINOADLT,CIRBIAGE,CIHOWOFT,CIASSIST,CIINTFER,CIFAMCAR,CIHCPROF,CIMEDS,CIDIAGAZ,WHRTST9,HIVRDTS2,CHIMRCVE,METVAL1_,METVAL2_,ACTINT1_,ACTINT2_,_MINACT1,_MINACT2,PAMISS_,PAMIN1_,PAMIN2_,PAMIN_,PAVIGM1_,PAVIGM2_,PAVIGMN_,_PACAT,_PAINDEX,_PA150R1,_PA300R1,_PA3002L,_PAREC,_PASTAER
0,1.0,1.0,b'01292015',b'01',b'29',b'2015',1200.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,3.0,1.000000e+00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,15.0,18.0,10.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,1.0,1.0,2.0,3.0,NaN,2.0,1.0,4.0,1.0,2.0,NaN,1.0,2.0,8.0,88.0,3.0,2.0,280.0,510.0,NaN,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,3.0,NaN,2.0,3.0,888.0,NaN,NaN,NaN,305.0,310.0,320.0,310.0,305.0,101.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,6.0,1.0,1.0,112014.0,1.0,1.0,1.0,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',3.0,11011.0,28.78156,3.0,86.344681,NaN,NaN,NaN,NaN,1.0,0.614125,341.384853,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,b'01202015',b'01',b'20',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,1.0,5.397605e-79,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,88.0,88.0,NaN,2.0,1.0,1.0,4.0,3.0,NaN,1.0,4.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,2.0,2.0,6.0,1.0,2.0,NaN,2.0,2.0,3.0,88.0,1.0,1.0,165.0,508.0,NaN,1.0,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,3.0,888.0,NaN,NaN,NaN,302.0,305.0,302.0,202.0,202.0,304.0,1.0,64.0,212.0,100.0,69.0,212.0,100.0,888.0,NaN,NaN,NaN,NaN,3.0,2.0,NaN,NaN,2.0,2.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0,5.0,NaN,5.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',1.0,2.0,NaN,NaN,2.0,60.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',5.0,11011.0,28.78156,1.0,28.781560,NaN,NaN,NaN,NaN,9.0,NaN,108.060903,1.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0,3.0,2.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,1.0,b'02012015',b'02',b'01',b'2015',1200.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.000000e+00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,15.0,88.0,88.0,1.0,2.0,2.0,1.0,3.0,NaN,1.0,1.0,1.0,7.0,2.0,1.0,2.0,NaN,2.0,1.0,2.0,1.0,2.0,2.0,3.0,NaN,2.0,2.0,4.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,99.0,2.0,158.0,511.0,NaN,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',5.0,11011.0,28.78156,2.0,57.563120,NaN,NaN,NaN,NaN,1.0,0.614125,255.264797,2.0,9.0,1.0,1.0,2.0,NaN,1.0,1.0,3.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,1.0,b'01142015',b'01',b'14',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,3.0,1.000000e+00,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,30.0,30.0,30.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,1.0,1.0,2.0,3.0,NaN,2.0,1.0,4.0,1.0,2.0,NaN,1.0,2.0,8.0,1.0,8.0,2.0,180.0,507.0,NaN,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,555.0,101.0,555.0,301.0,301.0,201.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,8.0,1.0,1.0,777777.0,5.0,1.0,9.0,NaN,NaN,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,1.0,1.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',4.0,7.0,NaN,NaN,NaN,97.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',3.0,11011.0,28.78156,3.0,86.344681,NaN,NaN,NaN,NaN,1.0,0.614125,341.384853,2.0,1.0,2.0,1.0,2.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,1.0,b'01142015',b'01',b'14',b'2015',1100.0,2.015000e+09,2.015000e+09,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.000000e+00,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,20.0,88.0,30.0,1.0,1.0,2.0,1.0,3.0,NaN,1.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,3.0,NaN,2.0,1.0,5.0,1.0,2.0,NaN,2.0,2.0,8.0,88.0,77.0,1.0,142.0,504.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,777.0,102.0,203.0,204.0,310.0,320.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,888.0,1.0,1.0,1.0,7.0,1.0,2.0,NaN,NaN,1.0,1.0,777777.0,1.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,1.0,777.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,1.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,b'',5.0,5.0,NaN,NaN,NaN,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,b'',b'',3.0,11011.0,28.78156,2.0,57.563120,NaN,NaN,NaN,NaN,9.0,NaN,258.682223,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df_selected = df[['DIABETE3', '_BMI5', '_RFBMI5', '_RFHYPE5', 
                  'TOLDHI2', '_CHOLCHK', 'CHCKIDNY', 'SMOKE100', 
                  '_RFDRHV5', 'CVDSTRK3', '_MICHD', '_TOTINDA', 
                  '_FRTLT1', '_VEGLT1', 'GENHLTH', 'PHYSHLTH', 
                  'MENTHLTH', 'DIFFWALK', 'HLTHPLN1', 'MEDCOST', 
                  'CHECKUP1', 'SEX', '_AGEG5YR']]
df_selected.shape

(2380047, 23)

In [21]:
df_selected.head()

,DIABETE3,_BMI5,_RFBMI5,_RFHYPE5,TOLDHI2,_CHOLCHK,CHCKIDNY,SMOKE100,_RFDRHV5,CVDSTRK3,_MICHD,_TOTINDA,_FRTLT1,_VEGLT1,GENHLTH,PHYSHLTH,MENTHLTH,DIFFWALK,HLTHPLN1,MEDCOST,CHECKUP1,SEX,_AGEG5YR
0,3.0,4018.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,5.0,15.0,18.0,1.0,1.0,2.0,1.0,2.0,9.0
1,3.0,2509.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,3.0,88.0,88.0,2.0,2.0,1.0,4.0,2.0,7.0
2,3.0,2204.0,1.0,1.0,1.0,1.0,2.0,NaN,9.0,1.0,NaN,9.0,9.0,9.0,4.0,15.0,88.0,NaN,1.0,2.0,1.0,2.0,11.0
3,3.0,2819.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,5.0,30.0,30.0,1.0,1.0,1.0,1.0,2.0,9.0
4,3.0,2437.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,9.0,1.0,5.0,20.0,88.0,2.0,1.0,2.0,1.0,2.0,9.0

In [22]:
df_selected = df_selected.dropna()
df_selected.shape

(343606, 23)

In [23]:
df_selected['DIABETE3'].value_counts()

DIABETE3
3.0    284625
1.0     49500
4.0      6516
2.0      2591
7.0       333
9.0        41
Name: count, dtype: int64

In [24]:
# 0 is for no diabetes or only during pregnancy, 1 is for pre-diabetes or borderline diabetes, 2 is for yes diabetes
df_selected['DIABETE3'] = df_selected['DIABETE3'].replace({2:0, 3:0, 1:2, 4:1})
df_selected = df_selected[df_selected.DIABETE3 != 7]
df_selected = df_selected[df_selected.DIABETE3 != 9]
df_selected.DIABETE3.unique()

array([0., 2., 1.])

In [25]:
def _replace_and_filter(df, col, replace_map=None, drop_values=None):
    """
    Helper function to replace values and filter out unwanted rows.

    Args:
        df (pd.DataFrame): Input dataframe.
        col (str): Column name to process.
        replace_map (dict, optional): Mapping for value replacement.
        drop_values (list, optional): Values to remove from the column.

    Returns:
        pd.DataFrame: Updated dataframe.
    """
    if replace_map:
        df[col] = df[col].replace(replace_map)
    if drop_values:
        df = df[~df[col].isin(drop_values)]
    return df


def preprocess_health_data(df):
    """
    Cleans and preprocesses health survey data for downstream ML tasks.

    Transformations include:
    - Binary encoding of categorical variables
    - Removal of invalid/missing responses (e.g., 7, 9, 77, 99)
    - Normalization of BMI values
    - Preservation of ordinal features where appropriate

    Args:
        df (pd.DataFrame): Raw input dataframe.

    Returns:
        pd.DataFrame: Cleaned and processed dataframe.
    """

    df = df.copy()

    # Binary / categorical cleaning
    df = _replace_and_filter(df, '_RFHYPE5', {1: 0, 2: 1}, [9])
    df = _replace_and_filter(df, 'TOLDHI2', {2: 0}, [7, 9])
    df = _replace_and_filter(df, '_CHOLCHK', {2: 0, 3: 0}, [9])
    df = _replace_and_filter(df, 'SMOKE100', {2: 0}, [7, 9])
    df = _replace_and_filter(df, 'CVDSTRK3', {2: 0}, [7, 9])
    df = _replace_and_filter(df, '_MICHD', {2: 0})
    df = _replace_and_filter(df, '_TOTINDA', {2: 0}, [9])
    df = _replace_and_filter(df, '_FRTLT1', {2: 0}, [9])
    df = _replace_and_filter(df, '_VEGLT1', {2: 0}, [9])
    df = _replace_and_filter(df, '_RFDRHV5', {1: 0, 2: 1}, [9])
    df = _replace_and_filter(df, 'HLTHPLN1', {2: 0}, [7, 9])
    df = _replace_and_filter(df, 'MEDCOST', {2: 0}, [7, 9])
    df = _replace_and_filter(df, 'DIFFWALK', {2: 0}, [7, 9])
    df = _replace_and_filter(df, 'SEX', {2: 0})

    # Ordinal / filtered only
    df = _replace_and_filter(df, 'GENHLTH', drop_values=[7, 9])
    df = _replace_and_filter(df, '_AGEG5YR', drop_values=[14])

    # Mental & physical health days
    df = _replace_and_filter(df, 'MENTHLTH', {88: 0}, [77, 99])
    df = _replace_and_filter(df, 'PHYSHLTH', {88: 0}, [77, 99])

    # BMI scaling
    df['_BMI5'] = (df['_BMI5'] / 100).round(0)

    return df

In [26]:
df_selected = preprocess_health_data(df_selected)
print(df_selected.shape)
df_selected.head()

(288259, 23)

,DIABETE3,_BMI5,_RFBMI5,_RFHYPE5,TOLDHI2,_CHOLCHK,CHCKIDNY,SMOKE100,_RFDRHV5,CVDSTRK3,_MICHD,_TOTINDA,_FRTLT1,_VEGLT1,GENHLTH,PHYSHLTH,MENTHLTH,DIFFWALK,HLTHPLN1,MEDCOST,CHECKUP1,SEX,_AGEG5YR
0,0.0,40.0,2.0,1.0,1.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,15.0,18.0,1.0,1.0,0.0,1.0,0.0,9.0
1,0.0,25.0,2.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,4.0,0.0,7.0
3,0.0,28.0,2.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0,30.0,30.0,1.0,1.0,1.0,1.0,0.0,9.0
5,0.0,27.0,2.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,11.0
6,0.0,24.0,1.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,2.0,0.0,3.0,0.0,1.0,0.0,1.0,0.0,11.0

In [27]:
df_selected['DIABETE3'].value_counts()

DIABETE3
0.0    242420
2.0     40489
1.0      5350
Name: count, dtype: int64

In [ ]:
final_df = df_selected.rename(columns = {
    'DIABETE3':'isDiabetic', 
    '_RFHYPE5':'HighBP',  
    'TOLDHI2':'HighChol', 
    '_CHOLCHK':'CholCheck', 
    '_BMI5':'BMI', 
    'SMOKE100':'Smoker', 
    'CVDSTRK3':'Stroke', 
    '_MICHD':'HeartDiseaseorAttack', 
    '_TOTINDA':'PhysActivity', 
    '_FRTLT1':'Fruits', 
    '_VEGLT1':"Veggies", 
    '_RFDRHV5':'HvyAlcoholConsump', 
    'HLTHPLN1':'AnyHealthcare', 
    'MEDCOST':'NoDocbcCost', 
    'GENHLTH':'GenHlth', 
    'MENTHLTH':'MentHlth', 
    'PHYSHLTH':'PhysHlth', 
    'DIFFWALK':'DiffWalk', 
    'SEX':'Sex', 
    '_AGEG5YR':'Age'
})

In [14]:
final_df.head()

,isDiabetic,BMI,_RFBMI5,HighBP,HighChol,CholCheck,CHCKIDNY,Smoker,HvyAlcoholConsump,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,GenHlth,PhysHlth,MentHlth,DiffWalk,AnyHealthcare,NoDocbcCost,CHECKUP1,Sex,Age
0,0.0,40.0,2.0,1.0,1.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,15.0,18.0,1.0,1.0,0.0,1.0,0.0,9.0
1,0.0,25.0,2.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,4.0,0.0,7.0
3,0.0,28.0,2.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0,30.0,30.0,1.0,1.0,1.0,1.0,0.0,9.0
5,0.0,27.0,2.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,11.0
6,0.0,24.0,1.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,2.0,0.0,3.0,0.0,1.0,0.0,1.0,0.0,11.0

In [16]:
final_df['isDiabetic'] = final_df['isDiabetic'].astype('category')
final_df.head()

,isDiabetic,BMI,_RFBMI5,HighBP,HighChol,CholCheck,CHCKIDNY,Smoker,HvyAlcoholConsump,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,Veggies,GenHlth,PhysHlth,MentHlth,DiffWalk,AnyHealthcare,NoDocbcCost,CHECKUP1,Sex,Age
0,0.0,40.0,2.0,1.0,1.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,5.0,15.0,18.0,1.0,1.0,0.0,1.0,0.0,9.0
1,0.0,25.0,2.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,4.0,0.0,7.0
3,0.0,28.0,2.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0,30.0,30.0,1.0,1.0,1.0,1.0,0.0,9.0
5,0.0,27.0,2.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,11.0
6,0.0,24.0,1.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,2.0,0.0,3.0,0.0,1.0,0.0,1.0,0.0,11.0

In [28]:
final_df['isDiabetic'].value_counts()

isDiabetic
0.0    242420
2.0     40489
1.0      5350
Name: count, dtype: int64

In [29]:
# final sanity check
final_df.isnull().sum()

isDiabetic              0
BMI                     0
_RFBMI5                 0
HighBP                  0
HighChol                0
CholCheck               0
CHCKIDNY                0
Smoker                  0
HvyAlcoholConsump       0
Stroke                  0
HeartDiseaseorAttack    0
PhysActivity            0
Fruits                  0
Veggies                 0
GenHlth                 0
PhysHlth                0
MentHlth                0
DiffWalk                0
AnyHealthcare           0
NoDocbcCost             0
CHECKUP1                0
Sex                     0
Age                     0
dtype: int64

In [19]:
final_df.to_parquet('/Users/other/Documents/Sweet-Sense-AI/data/dataset/data.parquet', index=False)